apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - daemonset.yaml
  - hpa.yaml

commonLabels:
  managed-by: kustomize

namespace: default
